### ISSUE TITLE
Keys and notes stick

### ISSUE THREAD

**Issue by AliSolaiman** [blairjordan/pianoboi#1]
It would be nice if note(s) gets cleared from the sheet after lifting the input key coming from the MIDI keyboard (also gets cleared from the piano roll)

**Comment by blairjordan** [comment]
I wasn't able to replicate this issue. What OS and keyboard are you running?

**Comment by blairjordan** [comment]
This one is impossible to diagnose without more info so I'll close it for now. 
Will re-open if I can get more detail.
 
It's possibly related to the messages sent by your midi controller.

This is a great tool for diagnosing midi issues which I've used in the past:
http://www.midiox.com/
